import API from './axios';
export const getDashboardStats = () => API.get('/admin/stats').then(r => r.data);
export const getAdminVehicles = (params) => API.get('/admin/vehicles', { params }).then(r => r.data);
export const createAdminVehicle = (data) => API.post('/admin/vehicles', data).then(r => r.data);
export const updateAdminVehicle = (id, data) => API.put(`/admin/vehicles/${id}`, data).then(r => r.data);
export const deleteAdminVehicle = (id) => API.delete(`/admin/vehicles/${id}`).then(r => r.data);
export const toggleVehicleAvailability = (id) => API.patch(`/admin/vehicles/${id}/toggle`).then(r => r.data);
export const getAdminBookings = (params) => API.get('/admin/bookings', { params }).then(r => r.data);
export const updateBookingStatus = (id, data) => API.put(`/admin/bookings/${id}/status`, data).then(r => r.data);
export const getAdminCustomers = (params) => API.get('/admin/customers', { params }).then(r => r.data);
export const toggleBlockCustomer = (id) => API.patch(`/admin/customers/${id}/block`).then(r => r.data);
export const getAdminPayments = (params) => API.get('/admin/payments', { params }).then(r => r.data);
export const processRefund = (id) => API.post(`/admin/payments/${id}/refund`).then(r => r.data);
export const getAdminReviews = () => API.get('/admin/reviews').then(r => r.data);
export const deleteAdminReview = (id) => API.delete(`/admin/reviews/${id}`).then(r => r.data);
export const getRevenueReport = () => API.get('/admin/reports/revenue').then(r => r.data);
export const getVehicleReport = () => API.get('/admin/reports/vehicles').then(r => r.data);
export const getBookingReport = () => API.get('/admin/reports/bookings').then(r => r.data);
export const getCustomerReport = () => API.get('/admin/reports/customers').then(r => r.data);
